name: VSA Website CI

#Triggers
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  #Build the Spring Boot Backend
  backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: vsa_db_test
          POSTGRES_USER: vsa_user
          POSTGRES_PASSWORD: vsa_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        working-directory: ./backend
        run: ./mvnw clean install -DskipTests

      - name: Run tests with Maven
        working-directory: ./backend
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/vsa_db_test
          SPRING_DATASOURCE_USERNAME: vsa_user
          SPRING_DATASOURCE_PASSWORD: vsa_password
        run: ./mvnw test


  #Build React Frontend
  frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build React app
        working-directory: ./frontend
        run: npm run build